### ISSUE TITLE
Inspect object has no attribute date_format

### ISSUE THREAD

**Issue by linville** [atac/c10-tools#19]
Inspecting a Chapter 10 file for just messages of type 0x30 errors out attempting to access a non-existent `date_format` attribute of the inspect object.

```sh
% pdm run c10 inspect path/to/file.c10 -t 0x30
-----------------------------------------------------------------------------------------------
| Channel | Type | Sequence | Size    | Time                        | Valid | Offset          |
-----------------------------------------------------------------------------------------------
'Inspect' object has no attribute 'date_format' at 0
'Inspect' object has no attribute 'date_format' at 336
... [snip] ...
```

Appears to be an issue with the following line: https://github.com/atac/c10-tools/blob/c49dd024afa3d35b134b1cb5299dc47a8ac93563/c10_tools/inspect.py#L75

I've worked around it by modifying that line to use `getattr(..)` to access the attribute (but wasn't quite confident if that was the fix or if it should just be initialized in `__init__`).

Reproduceable with Python 3.9 and 3.10.

**Comment by mcferrill** [comment]
That looks reasonable. Are you able to submit a pull request to that effect? Bonus points for tests.

**Comment by linville** [comment]
Submitted `getattr` change w/ test that checks inspect filtering expected output.

Probably out of scope for this PR, but I had to bump Pytest to a newer version to [get this fix](https://github.com/pytest-dev/pytest/pull/8540) to test with Python 3.10.

**Comment by mcferrill** [comment]
Looks great! Let's get this merged!

I'll make a note to review dependencies and pick up that pytest update. Thanks for calling that out.
